name: NPM Release

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
          node-version: 16.7.0
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.14.6
          run_install: true
      - name: Build
        run: pnpm build
      - uses: JS-DevTools/npm-publish@v1
        with:
          package: package.json
          token: ${{ secrets.NPM_TOKEN }}
